insightsengineering/teal.modules.clinical

R/tm_t_abnormality.R, R/tm_t_abnormality_by_worst_grade.R, R/tm_t_shift_by_grade.R, tests/testthat/test-tm_t_abnormality.R, tests/testthat/test-tm_t_abnormality_by_worst_grade.R, tests/testthat/test-tm_t_shift_by_grade.R
Updated tm_t_shift_by_grade, tm_t_abnormality and tm_t_abnormality_by_worst_grade with indents. Indents should be reflected in LBT15, LBT14, and LBT07. 
Refer to https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/124 
closes #508
=> increase indent teal outputs

NEWS.md, R/tm_g_barchart_simple.R
Closes #520 fyi @donyunardi 
So this fails as [here](https://github.com/insightsengineering/teal.modules.clinical/blob/047c3d40bb7e9c44e43913ed71adbd3191c95a8b/R/tm_g_barchart_simple.R#L424)
as inside the teal.widgets function it cannot find the `column_annotation_label, moving the substitute outside seems to fix it
Test with example in issue, roxygen example etc.
=> fix barchart

R/tm_g_barchart_simple.R, R/tm_t_shift_by_grade.R
closes https://github.com/insightsengineering/teal.modules.clinical/issues/526
=> fix tm_g_barchart

R/tm_t_exposure.R, tests/testthat/test-tm_t_exposure.R
=> 590 Fix typo in `tm_t_exposure` footnote

R/tm_t_coxreg.R, R/tm_t_tte.R, tests/testthat/test-tm_t_coxreg.R, tests/testthat/test-tm_t_tte.R
Footnotes for these modules did not include selected values, only the field names.
Original issue: #587 
Original PR: #615 
Closes #623
=> Fix `tm_t_tte`, `tm_t_coxreg` footnotes

NEWS.md
=> 622 Clean up `teal.modules.clinical` NEWS

NEWS.md, R/tm_g_km.R, R/tm_t_coxreg.R, R/tm_t_tte.R, tests/testthat/test-tm_g_km.R, tests/testthat/test-tm_t_tte.R
=> 652 Fix TMC footnotes

R/tm_t_binary_outcome.R
=> Update line to produce output.

NEWS.md, R/tm_a_gee.R, man/template_a_gee.Rd, man/tm_a_gee.Rd
=> 681 Add titles/footnotes for `tm_a_gee`

R/tm_a_gee.R
=>  fix gee coefficient display

DESCRIPTION, NEWS.md, R/tm_g_pp_vitals.R, man/tm_g_pp_vitals.Rd
closes #712 
Removed unused parameter `param` in `tm_g_pp_vitals`.
Updated example app and docs accordingly.
=> tmg_g_pp_vitals: remove param

R/tm_g_km.R, tests/testthat/test-tm_g_km.R
Closes #665.
Added expression that drops unused levels of faceting variable before plotting, so that empty panels are not plotted.
=> fix faceting in `tm_g_km`

staged_dependencies.yaml
Closes #710 
Merge with https://github.com/insightsengineering/scda/pull/116 and https://github.com/insightsengineering/scda.2022/pull/107
=> Remove `scda` and `scda.2022` from staged deps

R/validate_standard_inputs.R, man/validate_standard_inputs.Rd
=> Fix `validate_standard_inputs` example

NEWS.md, R/tm_t_summary.R, R/tm_t_summary_by.R
=> Fix `numeric_stats` bug in `tm_t_summary` and `tm_t_summary_by`

DESCRIPTION, R/tm_g_pp_adverse_events.R, R/tm_g_pp_therapy.R, R/tm_g_pp_vitals.R
=> 804 deprecation notes in `ggplot2`

R/tm_g_pp_patient_timeline.R
Fixes insightsengineering/teal.reporter#196
`teal.modules.clinical:::bracket_expr` does some nasty stuff with long expression. Precisely, is starts `else` from new line
```
if () {
...
}
else {
...
}
```
This function is super fragile. For example this fails:
```
call <- quote(
if (condition) {
1
} else {
2
}
)
teal.modules.clinical:::bracket_expr(call)
#2: if
#3: condition
^
```
=> Can't add reporter in patients timeline module

NEWS.md, R/tm_g_pp_adverse_events.R, R/tm_g_pp_patient_timeline.R, R/tm_g_pp_therapy.R, R/tm_g_pp_vitals.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, R/tm_t_pp_prior_medication.R, R/tm_t_summary.R
- Fixes #821
Use [`patient-profile`](https://github.com/insightsengineering/teal.gallery/blob/main/patient-profile/app.R) app from `teal.gallery`, or the code below.
Note: the code below that adds 2 `tm_t_summary` modules to patient-profile _(the 2nd doesn't use `dataname = "ADSL"` to show that `ADSL` is added as `parentname`)_
<details>
<summary>See to code</summary>
```R
pkgload::load_all()
library(teal.modules.clinical)
library(teal.modules.general)
library(scda)
library(scda.2022)
options(shiny.useragg = FALSE)
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
ADSL <- synthetic_cdisc_data("latest")$adsl
ADMH <- synthetic_cdisc_data("latest")$admh
ADAE <- synthetic_cdisc_data("latest")$adae
ADCM <- …
```
=> Patient Profile Modules only show relevant datanames

NEWS.md, R/arm_ref_comp.R, R/tm_t_coxreg.R, tests/testthat/_snaps/tm_t_coxreg.md
=> Fix `tm_t_coxreg` errors when applying filters

DESCRIPTION, NEWS.md, R/tm_g_pp_adverse_events.R, R/tm_g_pp_therapy.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, man/template_basic_info.Rd, man/template_laboratory.Rd, man/template_medical_history.Rd, staged_dependencies.yaml, tests/testthat/_snaps/tm_t_pp_medical_history.md
Closes #816 
Last commit implements `rlistings` - without this we can only do a workaround as titles can't be directly implemented in regular data frames.
Note: If we use the `rlistings` package we will also need to update staged.dependencies in `rlistings`.
=> Display Patient ID in relevant templates, clean up data tables in reports

NEWS.md, R/tm_g_lineplot.R, man/template_g_lineplot.Rd, man/tm_g_lineplot.Rd
=> Add option to remove interval in `tm_g_lineplot`

R/tm_t_summary.R
```
ADSL$EOSDY[1] <- NA_integer_
stopifnot(
any(is.na(ADSL$EOSDY)),
any(is.na(ADSL$DCSREAS))
)
app <- init(
ADSL = ADSL,
code = "
ADSL$EOSDY[1] <- NA_integer_
stopifnot(
any(is.na(ADSL$EOSDY)),
any(is.na(ADSL$DCSREAS))
)
"
),
tm_t_summary(
label = "Demographic Table",
dataname = "ADSL",
arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
add_total = TRUE,
summarize_vars = choices_selected(
c("SEX", "RACE", "BMRKR2", "EOSDY", "DCSREAS", "AGE"),
c("SEX", "RACE")
),
useNA = "ifany"
)
)
)
```
=> `tdata` to `teal_data` - `tm_t_summary`

R/tm_t_shift_by_arm_by_worst.R
```
ADEG <- tmc_ex_adeg
app <- init(
ADSL = ADSL,
ADEG = ADEG,
code = "
ADEG <- tmc_ex_adeg
"
),
tm_t_shift_by_arm_by_worst(
label = "Shift by Arm Table",
dataname = "ADEG",
variable_choices(ADSL, subset = c("ARM", "ARMCD")),
),
value_choices(ADEG, "PARAMCD"),
selected = "ECGINTP"
),
worst_flag_var = choices_selected(
variable_choices(ADEG, c("WORS02FL", "WORS01FL")),
selected = "WORS02FL"
),
worst_flag = choices_selected(
value_choices(ADEG, "WORS02FL"),
selected = "Y", fixed = TRUE
),
aval_var = choices_selected(
variable_choices(ADEG, c("AVALC", "ANRIND")),
selected = "AVALC"
),
base_var = choices_selected( …
```
=> `tdata` to `teal_data` - `tm_t_shift_by_arm_by_worst`

R/tm_t_shift_by_arm.R
```
ADEG <- tmc_ex_adeg
app <- init(
ADSL = ADSL,
ADEG = ADEG,
code = "
ADEG <- tmc_ex_adeg
"
),
tm_t_shift_by_arm(
label = "Shift by Arm Table",
dataname = "ADEG",
variable_choices(ADSL, subset = c("ARM", "ARMCD")),
),
value_choices(ADEG, "PARAMCD"),
selected = "HR"
),
visit_var = choices_selected(
value_choices(ADEG, "AVISIT"),
selected = "POST-BASELINE MINIMUM"
),
aval_var = choices_selected(
variable_choices(ADEG, subset = "ANRIND"),
selected = "ANRIND", fixed = TRUE
),
base_var = choices_selected(
variable_choices(ADEG, subset = "BNRIND"),
selected = "BNRIND", fixed = TRUE
),
useNA = "ifany"
)
)
)
shinyApp(app$ui, …
```
=> `tdata` to `teal_data` - `tm_t_shift_by_arm`

R/tm_t_smq.R
```
names_baskets <- grep("^(SMQ|CQ).*NAM$", names(ADAE), value = TRUE)
names_scopes <- grep("^SMQ.*SC$", names(ADAE), value = TRUE)
cs_baskets <- choices_selected(
choices = variable_choices(ADAE, subset = names_baskets),
selected = names_baskets
)
cs_scopes <- choices_selected(
choices = variable_choices(ADAE, subset = names_scopes),
selected = names_scopes,
fixed = TRUE
)
})
datanames <- c("ADSL", "ADAE")
app <- init(
data = data,
tm_t_smq(
label = "Adverse Events by SMQ Table",
dataname = "ADAE",
choices = variable_choices(data[["ADSL"]], subset = c("ARM", …
```
=> `tdata`  to  `teal_data` - `tm_t_smq`

R/tm_t_events.R
```
app <- teal::init(
ADSL = ADSL,
ADAE = ADAE,
code = "
"
),
tm_t_events(
label = "Adverse Event Table",
dataname = "ADAE",
arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
llt = choices_selected(
choices = variable_choices(ADAE, c("AETERM", "AEDECOD")),
selected = c("AEDECOD")
),
hlt = choices_selected(
choices = variable_choices(ADAE, c("AEBODSYS", "AESOC")),
selected = "AEBODSYS"
),
add_total = TRUE,
event_type = "adverse event"
)
)
)
```
=> `tdata` to `teal_data` - `tm_t_events`

R/tm_t_logistic.R
```
dplyr::filter(PARAMCD %in% c("BESRSPI", "INVET"))
ref = "ARM B",
),
ARM = list(
)
)
app <- init(
ADSL = ADSL,
ADRS = ADRS,
code = "
dplyr::filter(PARAMCD %in% c(\"BESRSPI\", \"INVET\"))
"
),
tm_t_logistic(
label = "Logistic Regression",
dataname = "ADRS",
choices = variable_choices(ADRS, c("ARM", "ARMCD")),
),
choices = value_choices(ADRS, "PARAMCD", "PARAM"),
selected = "BESRSPI"
),
cov_var = choices_selected(
choices = …
```
=> `tdata` to `teal_data` - `tm_t_logistic`

R/tm_t_events_by_grade.R
```
lbls_adae <- formatters::var_labels(tmc_ex_adae)
ADAE <- tmc_ex_adae %>%
dplyr::mutate_if(is.character, as.factor) #' be certain of having factors
formatters::var_labels(ADAE) <- lbls_adae
})
datanames <- c("ADSL", "ADAE")
app <- init(
data = data,
tm_t_events_by_grade(
label = "Adverse Events by Grade Table",
dataname = "ADAE",
arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
llt = choices_selected(
choices = variable_choices(data[["ADAE"]], c("AETERM", "AEDECOD")),
selected = c("AEDECOD")
),
hlt = choices_selected(
choices = variable_choices(data[["ADAE"]], c("AEBODSYS", "AESOC")),
selected = …
```
=> `tdata` to `teal_data` - `tm_t_events_by_grade`

R/tm_t_ancova.R
```r
ADQS <- tmc_ex_adqs
ARM = list(
),
ref = "ARM B",
)
)
app <- init(
ADSL = ADSL,
ADQS = ADQS,
code = "
ADQS <- tmc_ex_adqs
"
),
tm_t_ancova(
label = "ANCOVA Table",
dataname = "ADQS",
avisit = choices_selected(
choices = value_choices(ADQS, "AVISIT"),
selected = "WEEK 1 DAY 8"
),
choices = variable_choices(ADSL, c("ARM", "ACTARMCD", "ARMCD")),
selected = "ARMCD"
),
aval_var = choices_selected(
choices = variable_choices(ADQS, c("CHG", "AVAL")),
selected = "CHG"
),
cov_var = choices_selected(
choices = variable_choices(ADQS, …
```
=> `tdata` to `teal_data` - `tm_t_ancova`

DESCRIPTION, R/tm_a_gee.R, R/tm_a_mmrm.R, R/tm_g_barchart_simple.R, R/tm_g_ci.R, R/tm_t_abnormality.R, R/tm_t_abnormality_by_worst_grade.R, R/tm_t_events.R, R/tm_t_events_by_grade.R, R/tm_t_events_patyear.R, R/tm_t_events_summary.R, R/tm_t_exposure.R, R/tm_t_logistic.R, R/tm_t_mult_events.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, R/tm_t_pp_prior_medication.R, R/tm_t_shift_by_arm.R, R/tm_t_shift_by_arm_by_worst.R, R/tm_t_shift_by_grade.R, R/tm_t_smq.R, R/tm_t_summary.R, R/tm_t_summary_by.R, R/tm_t_tte.R
Added `shiny::` to `isolate` and `reactive` calls.
Removed duplicate dependency on `teal_data`.
=> fix missing prefixes

DESCRIPTION, NEWS.md, R/tm_g_pp_vitals.R
closes #895 
Error thrown in `qenv` is caused by following line 
```r
ggplot2::scale_y_continuous(
breaks = seq(0, max(vitals[[xaxis_char]], na.rm = TRUE), 50),
minor_breaks = seq(0, max(vitals[[aval_char]], na.rm = TRUE), 10)
)
```
Problem with this line is that `vitals[[xaxis_char]]` in our example is a `difftime` (column "ADY"). 
`x` as `difftime` causes also warning in the first line of ggplot call (`ggplot2::ggplot(data = vitals, mapping = ggplot2::aes(x = xaxis))`) so I decided to include conversion to integer in `mutate`. More in comments.
=> fix `tm_g_pp_vitals`

DESCRIPTION, NEWS.md, R/tm_g_lineplot.R, man/tm_g_lineplot.Rd
=> Fix bug forcing `tm_g_lineplot` to initialize with a table

R/tm_t_shift_by_arm.R, R/tm_t_shift_by_arm_by_worst.R, man/template_shift_by_arm.Rd, man/template_shift_by_arm_by_worst.Rd, man/tm_t_shift_by_arm.Rd
=> Clean up documentation for `tm_t_shift_by_arm`

.github/workflows/check.yaml, .github/workflows/docs.yaml
Since `teal.modules.clinical` now again [`Depends` on `tern >= 0.9.3`](https://github.com/insightsengineering/teal.modules.clinical/blob/bd513f0c33b81b5c98c0b366c564823068b1737c/DESCRIPTION#L31), I think we can change the workflow branch back from `install-tern-from-cran` to `main` (changed in https://github.com/insightsengineering/teal.modules.clinical/pull/922).
=> Change r.pkg.template branch to main

R/argument_convention.R, R/tm_t_tte.R, man/module_arguments.Rd, man/tm_a_gee.Rd, man/tm_a_mmrm.Rd, man/tm_g_forest_rsp.Rd, man/tm_g_forest_tte.Rd, man/tm_g_km.Rd, man/tm_t_abnormality.Rd, man/tm_t_abnormality_by_worst_grade.Rd, man/tm_t_ancova.Rd, man/tm_t_binary_outcome.Rd, man/tm_t_coxreg.Rd, man/tm_t_events.Rd, man/tm_t_events_by_grade.Rd, man/tm_t_events_patyear.Rd, man/tm_t_events_summary.Rd, man/tm_t_mult_events.Rd, man/tm_t_shift_by_arm.Rd, man/tm_t_shift_by_arm_by_worst.Rd, man/tm_t_shift_by_grade.Rd, man/tm_t_smq.Rd, man/tm_t_summary.Rd, man/tm_t_summary_by.Rd, man/tm_t_tte.Rd
Just a small doc change to stay consistent throughout the param function docs.
As we're using `teal.transform::choices_selected` and `teal.transform::data_extract_spec` in almost all the places.
=> Append the teal.transform namespace to stay consistent

NEWS.md, R/tm_t_summary_by.R
Fixes #1082
Required version of `teal.data` should be updated after merging https://github.com/insightsengineering/teal.data/pull/301.
=> Allow `NULL` `paramcd` value in `tm_t_summary_by`

tests/testthat/_snaps/tm_t_summary_by.md
=> Update snapshots to fix tests

R/tm_t_logistic.R
Fixes #1044
* Rename output ID
Note: I don't think this is `NEWS.md` noteworthy.
=> Rename output IDE to prevent DOM conflicts

tests/testthat/test-examples.R
put up `skip_on_cran()` so that we don't run `rd_files()`
=> remove stop() in test-examples.R

NEWS.md, R/tm_t_binary_outcome.R, inst/WORDLIST, man/tm_t_binary_outcome.Rd
=> Expose `control` argument in `tm_t_binary_outcome`

tests/testthat/test-shinytest2-tm_g_forest_rsp.R
=> Wave 1 - `tm_g_forest_rsp` shinytests

tests/testthat/helper-TealAppDriver.R, tests/testthat/test-shinytest2-tm_a_gee.R
=> Wave 1 - `tm_a_gee` shinytests

tests/testthat/test-shinytest2-tm_g_pp_vitals.R
=> Wave 3 - `tm_g_pp_vitals` shinytest2

tests/testthat/test-shinytest2-tm_g_km.R, tests/testthat/test-shinytest2-tm_t_binary_outcome.R
=> Wave 4 - `tm_t_binary_outcome` shinytests

R/tm_g_pp_therapy.R, tests/testthat/test-shinytest2-tm_g_pp_therapy.R
Part of #1108
Module has very specific set of variables that don't allow for many choices
Fields not 100% tested:
- `cmdecod`: selected variable needs to be named CMDECOD due to limitation in module's logic
- `cmtrt`: Could not manipulate data for this field to have any change on output.
- It seems that it is only used when CMDECOD has long values
=> Wave 3 - `tm_g_pp_therapy` shinytest2

R/tm_t_exposure.R, man/template_exposure.Rd
this fixes https://github.com/insightsengineering/teal.modules.clinical/issues/1175
- `col_by_va`r is optional. but it fails on deselection.
-  The issue was resolved by updating the assertion and assigning a NULL value.
=> 1175 fixing validation on `col_by_var` variable.

.github/workflows/scheduled.yaml, DESCRIPTION
Part of https://github.com/insightsengineering/coredev-tasks/issues/546
Necessary bump to overcome a lack of binary on ppm snapshots that causes an error on minimum strategies for `scheduled` workflows.
=> Bumps `{rmarkdown}` minimal version

DESCRIPTION
closes #1192 
changes to rtables to help with "Teal app column widths" 
related [rtables PR ](https://github.com/insightsengineering/rtables/pull/873)
=> increase rtables dep version

NEWS.md, R/tm_t_events_patyear.R, man/tm_t_events_patyear.Rd, tests/testthat/_snaps/tm_t_events_patyear.md, tests/testthat/test-shinytest2-tm_t_events_patyear.R, tests/testthat/test-tm_t_events_patyear.R
=> Add functionality to `tm_t_events_patyear` to split columns by multiple (nested) variables

NEWS.md, R/tm_t_summary.R, man/template_summary.Rd, man/tm_t_summary.Rd, tests/testthat/_snaps/tm_t_summary.md, tests/testthat/test-tm_t_summary.R
Fixes #1204
Also deprecates `show_labels` argument to `template_summary` that's not used in the module.
=> Add option to `tm_t_summary` to include `arm_var` labels in table header

DESCRIPTION, NEWS.md, R/tm_g_lineplot.R, README.md, man/template_g_lineplot.Rd, man/tm_g_lineplot.Rd, tests/testthat/_snaps/tm_g_lineplot.md
=> Use `group_var` argument to `control_lineplot_vars` instead of deprecated `strata`

R/utils.R, tests/testthat/_snaps/utils.md
* Changed the separator in `h_concat_expr` to `\n` to avoid generating unparsable code such as in this example:
```{r}
q <- quote({
a <- 1
for (i in 1:7) {}
})
unparsable <- teal.modules.clinical:::h_concat_expr(q)
print(unparsable)
str2lang(unparsable) # Parse error, unexpected for
```
* From what I could tell, this does not affect Show R Code outputs (surprisingly)
=> fix: changed the separator in h_concat_expr

DESCRIPTION
=> Update DESCRIPTION tern to 0.9.6

R/tm_t_binary_outcome.R
Fixes #1228
* Reset the factor levels on`input_arm_var` before creating the table during validation.
=> reset factor level during validate

.pre-commit-config.yaml
Fixes https://github.com/insightsengineering/nestdevs-tasks/issues/85
- Add dependency to pre-commit configuration
=> Adds `roxy.shinylive` to pre-commit configuration

R/tm_g_pp_patient_timeline.R
<details>
<summary>Example using cowplot::add_sub with ggplot2</summary>
```r
devtools::load_all("../teal.modules.general")
devtools::load_all("../teal.reporter")
devtools::load_all("../teal")
devtools::load_all(".")
library(dplyr)
filter(USUBJID %in% ADAE$USUBJID)
ADCM <- tmc_ex_adcm %>%
mutate(
CMSTDY = case_when(
CMCAT == "medcl B" ~ 20,
CMCAT == "medcl C" ~ 150,
TRUE ~ 1
) %>% with_label("Study Day of Start of Medication"),
CMENDY = case_when(
CMCAT == "medcl B" ~ 700,
CMCAT == "medcl C" ~ 1000,
TRUE ~ 500
) %>% with_label("Study Day of End of Medication"),
CMASTDTM = ASTDTM,
CMAENDTM = AENDTM
)
})
join_keys(data) <- …
```
=> introduce decorators to `tm_g_pp_patient_timeline`

R/tm_g_pp_therapy.R, tests/testthat/test-shinytest2-tm_g_pp_therapy.R
Closes #1253 
The main issue was due to the fact that the `rlistings::as_listing()` [no longer accepts](https://github.com/insightsengineering/rlistings/pull/232) columns of the type "difftime" and the module code had was creating a listing with this column type.
The fix was to just convert this to character.
Code to reproduce (Please make sure you have the dev version of `rlistings` package to reproduce):
```r
library(rlistings)
ADCM <- teal.modules.clinical::tmc_ex_adcm
ADSL <- dplyr::filter(teal.modules.clinical::tmc_ex_adsl, USUBJID %in% ADCM$USUBJID)
ADCM$CMASTDTM <- ADCM$ASTDTM
ADCM$CMAENDTM <- ADCM$AENDTM
ADCM$ATIREL2 <- gsub("PRIOR", "PRIOR_CONCOMITANT", ADCM$ATIREL)
ADCM$CMDECOD2 <- sample(ADCM$CMDECOD, size = length(ADCM$CMDECOD))
ADCM$CMINDC2 <- sample(ADCM$CMINDC, size = …
```
=> Bring back tests for `tm_g_pp_therapy`

R/tm_t_coxreg.R, man/tm_t_coxreg.Rd
<details>
<summary>Example with decorator</summary>
```r
load_all("../teal.code")
load_all("../teal.data")
load_all("../teal")
load_all(".")
ref = "ARM B",
),
ARM = list(
)
)
substitute({
.var_to_replace <- rtables::insert_rrow(.var_to_replace, rtables::rrow(new_row)) …
```
=> Introduce decorators for `tm_t_coxreg`

R/tm_t_events.R, man/tm_t_events.Rd
<details>
<summary>Example with decorator</summary>
```r
load_all("../teal")
load_all(".")
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
ADSL <- data[["ADSL"]]
ADAE <- data[["ADAE"]]
substitute({
.var_to_replace <- rtables::insert_rrow(.var_to_replace, rtables::rrow(new_row))
)
)
}
app <- init( …
```
=> Introduce decorator for `tm_t_events`

R/tm_g_pp_adverse_events.R
Fixes #1272
- Similar fix that was applied in #1271
=> fixes error in adverse events when `ASTDY` is of difftime type

R/tm_t_logistic.R, man/tm_t_logistic.Rd
<details>
<summary>Working example</summary>
```r
pkgload::load_all("../teal.modules.clinical", export_all = FALSE)
substitute({
.var_to_replace <- rtables::insert_rrow(.var_to_replace, rtables::rrow(new_row))
)
)
}
library(dplyr)
filter(PARAMCD %in% c("BESRSPI", "INVET"))
})
join_keys(data) <- …
```
=> Adds decorators to `tm_t_logistic`

R/tm_t_summary.R, man/tm_t_summary.Rd
<details>
<summary>Working example</summary>
```r
pkgload::load_all("../teal.modules.clinical", export_all = FALSE)
substitute({
.var_to_replace <- rtables::insert_rrow(.var_to_replace, rtables::rrow(new_row))
)
)
}
ADSL$EOSDY[1] <- NA_integer_
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
ADSL <- data[["ADSL"]]
app …
```
=> Adds decorators to `tm_t_summary`

tests/testthat/test-shinytest2-tm_a_mmrm.R
Potentially closes #1258
_Potentially_, because I was not able to reproduce this issue in any way to know for sure that fixes the issue. I tested in macOS, linux (docker image our CI uses), and Windows machines after installing all the packages from the GitHub main branch and was unable to reproduce this behavior.
We can close the issue after we confirm the daily integration test is resolved.
Rationale for the change:
Since this module only works after the `Fit Model` button is clicked the shinytest2 logic goes as follows:
1. Initialize the `TealAppDriver` object using the `tm_a_mmrm()` module.
2. Click the `Fit Model` button.
3. Perform the test logic:
a. Select the `Output Type` 
b. Check for errors
c. Check if output changed
I think that when we start checking for errors we spot the …
=> Fix tmc integration test - Wait for shiny app idle after fit is clicked

R/tm_g_forest_rsp.R, R/tm_t_coxreg.R, R/tm_t_tte.R, R/utils.R, man/split_choices.Rd, man/template_coxreg_m.Rd, man/template_coxreg_u.Rd, man/template_forest_rsp.Rd, man/template_forest_tte.Rd, man/tm_g_forest_rsp.Rd, man/tm_g_forest_tte.Rd, man/tm_t_tte.Rd
Fixes #1231 
The links are correctly resolved to the package and R CMD check doesn't complain (with 2024-12-07 r87428 ucrt)
See https://github.com/insightsengineering/teal/issues/1420#issuecomment-2535506586 for a longer explanation.
=> Fix documentation note about links on r-devel

tests/testthat/test-examples.R
=> Stop R process if AppDriver fails in `test-examples`

tests/testthat/_snaps/tm_a_gee.md, tests/testthat/_snaps/tm_a_mmrm.md, tests/testthat/_snaps/tm_g_ci.md, tests/testthat/_snaps/tm_g_forest_rsp.md, tests/testthat/_snaps/tm_g_forest_tte.md, tests/testthat/_snaps/tm_g_km.md, tests/testthat/_snaps/tm_g_lineplot.md, tests/testthat/_snaps/tm_t_abnormality.md, tests/testthat/_snaps/tm_t_abnormality_by_worst_grade.md, tests/testthat/_snaps/tm_t_ancova.md, tests/testthat/_snaps/tm_t_binary_outcome.md, tests/testthat/_snaps/tm_t_coxreg.md, tests/testthat/_snaps/tm_t_events.md, tests/testthat/_snaps/tm_t_events_by_grade.md, tests/testthat/_snaps/tm_t_events_patyear.md, tests/testthat/_snaps/tm_t_events_summary.md, tests/testthat/_snaps/tm_t_exposure.md, tests/testthat/_snaps/tm_t_logisitic.md, tests/testthat/_snaps/tm_t_mult_events.md, tests/testthat/_snaps/tm_t_pp_medical_history.md, tests/testthat/_snaps/tm_t_shift_by_arm.md, tests/testthat/_snaps/tm_t_shift_by_arm_by_worst.md, tests/testthat/_snaps/tm_t_shift_by_grade.md, tests/testthat/_snaps/tm_t_smq.md, tests/testthat/_snaps/tm_t_summary.md, tests/testthat/_snaps/tm_t_summary_by.md, tests/testthat/_snaps/tm_t_tte.md
Part of https://github.com/insightsengineering/teal/issues/1371#issue-2575079391
- Tracks changes in the template code of the decorators feature branch
- Renames variables to be `plot`, `table` or (in case of multiple decoratable elements) `<name>_plot` and `<name>_table`
Manually triggered: https://github.com/insightsengineering/teal.modules.clinical/actions/runs/12359120026
[![Check 🛠](https://github.com/insightsengineering/teal.modules.clinical/actions/workflows/check.yaml/badge.svg?branch=snapshots%401187_decorate_output%40main)](https://github.com/insightsengineering/teal.modules.clinical/actions/workflows/check.yaml)
=> Decorators: Accepts new snapshot from `testthat::test()`

.github/workflows/scheduled.yaml, DESCRIPTION, NEWS.md
Running build https://github.com/insightsengineering/teal.modules.clinical/actions/runs/12806427331
Part of https://github.com/insightsengineering/nestdevs-tasks/issues/98
=> update packages for the scheduled build

.github/workflows/scheduled.yaml
Similar to https://github.com/insightsengineering/teal.modules.general/pull/830/files
Companion to that allows to use older MultiAssayExperiment and older SummarizedExperiment 
More explanation in here https://github.com/insightsengineering/teal.slice/pull/637#issuecomment-2607373951
https://github.com/insightsengineering/teal/pull/1460
https://github.com/insightsengineering/teal.slice/pull/637
=> simplify builds dependencies of extra-deps

R/utils.R
Fixes #1316
Companion in tmg https://github.com/insightsengineering/teal.modules.general/pull/835
There was an issue where decorators got duplicated when you passed a combination of named an unnamed decorators into the module. This module has 2 objects, so if you pass 1 unnamed decorators and one named, there should be only 3 decorators visible (1 unnamed passed to all 2, and one named pass to one named).
On feature branch
On main
<details><summary> Code </summary>
```r
pkgload::load_all(".", export_all = FALSE)
library(dplyr)
filter(USUBJID %in% ADAE$USUBJID)
ADAE$ASTDY <- structure(
as.double(ADAE$ASTDY, unit = attr(ADAE$ASTDY, "units", exact = TRUE)),
label = attr(ADAE$ASTDY, …
```
=> Duplicated decorators during an edge case of named and unnamed decorators

NEWS.md, R/tm_t_mult_events.R, man/tm_t_mult_events.Rd, teal.modules.clinical.Rproj, tests/testthat/test-shinytest2-tm_t_mult_events.R
=> Add `title_text` argument to `tm_t_mult_events()` to control dynamic title

.github/workflows/check.yaml
Related to https://github.com/insightsengineering/coredev-tasks/issues/580, as a followup on https://github.com/insightsengineering/r.pkg.template/pull/273
By enabling these options shinytest2 tests will only run when needed. 
This will help running faster tests on PR modifying just some modules.
=> Faster check times on CI

R/tm_g_forest_rsp.R, R/tm_g_forest_tte.R, man/template_forest_rsp.Rd, man/template_forest_tte.Rd, tests/testthat/_snaps/tm_g_forest_rsp.md, tests/testthat/_snaps/tm_g_forest_tte.md
Fixes the Forest plot module decorators mentioned [here](https://github.com/insightsengineering/teal.modules.clinical/pull/1348#issuecomment-2673521507)
- ❌ tm_g_forest_rsp - plot (ggplot2) **[plot decorator does not seem to work]**
- ❌ tm_g_forest_tte - plot (ggplot2) **[plot decorator does not seem to work]**
<details>
<summary>
Example app to test
</summary>
```r
pkgload::load_all()
caption_decorator <- function(default_caption = "I am a good decorator", .var_to_replace = "plot") {
label = "Caption",
ui = function(id) shiny::textInput(shiny::NS(id, "footnote"), "Footnote", value = default_caption),
substitute(
{
.var_to_replace <- .var_to_replace + ggplot2::labs(caption = footnote)
},
env = list(.var_to_replace = …
```
=> fix: make sure the decoration is applied to the forest plots

.github/workflows/scheduled.yaml, DESCRIPTION, NEWS.md
=> [skip vbump] upversion v0.10.0

DESCRIPTION
This PR updates all DESCRIPTION files to require teal.reporter (>= 0.5.0) and removes it from Remotes.
=> chore: bump teal.reporter dependency to 0.5.0 and remove from Remotes
