DESCRIPTION, NEWS.md, R/tm_g_pp_vitals.R, staged_dependencies.yaml
Closes #527 (must also merge insightsengineering/nestcolor#10)
=> 527 Update to use `nestcolor::color_palette`

DESCRIPTION, NEWS.md, R/tm_g_barchart_simple.R, R/tm_g_ci.R, R/tm_g_forest_rsp.R, R/tm_g_forest_tte.R, R/tm_g_ipp.R, R/tm_g_km.R, R/tm_g_lineplot.R, R/tm_g_pp_adverse_events.R, R/tm_g_pp_patient_timeline.R, R/tm_g_pp_therapy.R, R/tm_g_pp_vitals.R, man/tm_g_barchart_simple.Rd, man/tm_g_ci.Rd, man/tm_g_forest_rsp.Rd, man/tm_g_forest_tte.Rd, man/tm_g_ipp.Rd, man/tm_g_km.Rd, man/tm_g_lineplot.Rd, man/tm_g_pp_adverse_events.Rd, man/tm_g_pp_patient_timeline.Rd, man/tm_g_pp_therapy.Rd, man/tm_g_pp_vitals.Rd, vignettes/teal-modules-clinical.Rmd
=> 511 Implement `nestcolor` in TMC

R/tm_g_forest_rsp.R, R/tm_t_ancova.R, R/tm_t_tte.R, man/template_ancova.Rd, man/template_forest_rsp.Rd, man/template_tte.Rd
part of https://github.com/insightsengineering/teal.slice/issues/76
=> remove _FILTERED

R/tm_a_mmrm.R, R/tm_g_barchart_simple.R, R/tm_g_km.R, R/tm_t_coxreg.R, R/tm_t_logistic.R, R/tm_t_tte.R, inst/css/custom.css
linked to  https://github.com/insightsengineering/coredev-tasks/issues/225
* real update is only about 50 lines of code the rest is only a styler
- remove inline css rule
Almost all inlines was only to add the darkblue color to some text. I apply the already available  boostrap rule `text-primary` so the blue color is a little bit lighter still it is consistent with the rest design and is more elegant css.
=> rm inline - css tmc

R/tm_a_mmrm.R, R/tm_g_barchart_simple.R, R/tm_t_ancova.R, R/tm_t_events.R
=> 26 new chunks mh modules@26 new chunks@main

R/arm_ref_comp.R, R/tm_g_barchart_simple.R, R/tm_g_ci.R, R/tm_g_ipp.R, R/tm_g_pp_adverse_events.R, R/tm_g_pp_patient_timeline.R, R/tm_t_coxreg.R, R/tm_t_events_summary.R, R/tm_t_logistic.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, R/tm_t_pp_prior_medication.R, man/arm_ref_comp_observer.Rd
all 3 UNFILTERED data calls in cox could be easily replaced with filtered version, they are used only to check variables type:
https://github.com/insightsengineering/teal.modules.clinical/blob/e225371a7cc9c5eb27fad06798747a06f19862c7/R/tm_t_coxreg.R#L756-L770
https://github.com/insightsengineering/teal.modules.clinical/blob/e225371a7cc9c5eb27fad06798747a06f19862c7/R/tm_t_coxreg.R#L784-L786
https://github.com/insightsengineering/teal.modules.clinical/blob/e225371a7cc9c5eb27fad06798747a06f19862c7/R/tm_t_coxreg.R#L886-L905
=> tmc - quosure

NEWS.md, tests/testthat/test-tm_g_ci.R, tests/testthat/test-tm_g_lineplot.R, tests/testthat/test-tm_t_abnormality_by_worst_grade.R, tests/testthat/test-tm_t_shift_by_grade.R, tests/testthat/test-utils.R
Update all test files in tests/testthat/ from synthetic_cdisc_data("2021_05_05") or others to synthetic_cdisc_data("2022_02_28").
closes #474
=> Updated all test files in tests/testthat/ ("2022_02_28")

NEWS.md, R/tm_g_ci.R, tests/testthat/test-tm_g_ci.R
=> 564 Add more descriptive title/labels to `tm_g_ci`

NEWS.md, R/tm_g_forest_tte.R, R/tm_t_binary_outcome.R, R/tm_t_coxreg.R, man/template_coxreg_u.Rd, tests/testthat/test-tm_g_forest_tte.R, tests/testthat/test-tm_t_binary_outcome.R
=> 588 Add "Stratified by" Subtitles

NEWS.md, R/tm_g_ci.R
=> 592 Add visit subtitle to `tm_g_ci`

R/tm_g_barchart_simple.R, R/tm_g_ci.R, R/tm_g_forest_rsp.R, R/tm_g_forest_tte.R, R/tm_g_ipp.R, R/tm_g_pp_adverse_events.R, R/tm_g_pp_patient_timeline.R, R/tm_g_pp_therapy.R, R/tm_g_pp_vitals.R, R/tm_t_abnormality.R, R/tm_t_abnormality_by_worst_grade.R, R/tm_t_ancova.R, R/tm_t_binary_outcome.R, R/tm_t_coxreg.R, R/tm_t_events.R, R/tm_t_events_by_grade.R, R/tm_t_events_patyear.R, R/tm_t_logistic.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, R/tm_t_pp_prior_medication.R, R/tm_t_shift_by_arm.R, R/tm_t_shift_by_arm_by_worst.R, R/tm_t_shift_by_grade.R, R/tm_t_smq.R
Part of https://github.com/insightsengineering/teal.code/issues/67
along with https://github.com/insightsengineering/teal.code/pull/68
=> fixes after changes in teal.code

NEWS.md, R/tm_t_smq.R
=> 593 Fix `tm_t_smq` card name

NEWS.md, R/tm_t_events_patyear.R, man/tm_t_events_patyear.Rd, tests/testthat/test-tm_t_events_patyear.R
=> 561 Add CI Method footnote to `tm_t_events_patyear`

.github/workflows/check.yaml
No need for auto-updates for style checks.
=> Turn off auto-styling

NEWS.md, R/tm_g_km.R, tests/testthat/test-tm_g_km.R
=> 614 Add subtitle/footnotes to `tm_g_km`

NEWS.md, R/tm_t_binary_outcome.R
Example will run correctly after merging https://github.com/insightsengineering/tern/pull/718 
Closes #586
=> 586 Add Stratified Newcombe to Stratified Analysis CI Method Options for `tm_t_binary_oucome`

NEWS.md
Closes https://github.com/insightsengineering/sme-tasks/issues/470
=> Fix grammar in NEWS.md

R/tm_t_abnormality.R, tests/testthat/test-tm_t_abnormality.R
=> 633 Fix `tm_t_abnormality` footer

NEWS.md, R/tm_a_mmrm.R
Closes https://github.com/insightsengineering/coredev-tasks/issues/396
=> Add validation for `tm_a_mmrm` covariate/visit conflict

R/tm_t_ancova.R, R/tm_t_events_by_grade.R, R/tm_t_events_patyear.R, R/tm_t_summary_by.R, man/tm_t_ancova.Rd, man/tm_t_events_by_grade.Rd, man/tm_t_events_patyear.Rd, man/tm_t_summary_by.Rd
Closes #650 
This makes the modules which currently do not work behave like those that do (i.e. like tm_g_ipp and lots of others)
=> update roxygen for SRC

R/tm_a_mmrm.R
=> 525: parse cor_struct choices from tern.mmrm package

DESCRIPTION, NEWS.md, staged_dependencies.yaml
Don't merge until the other scda PRs are ready
Part of https://github.com/insightsengineering/teal/issues/760
Closes #662
=> Use scda.2022

DESCRIPTION, staged_dependencies.yaml
resolve staged.dependencies issue https://github.com/insightsengineering/chevron/actions/runs/3481860743/jobs/5832813891
Signed-off-by: Joe Zhu <sha.joe.zhu@gmail.com>
Fixes #nnn
=> Update staged_dependencies.yaml, adding tern.gee

R/tm_a_gee.R, tests/testthat/test-tm_a_gee.R
=> 679 Add tests for `tm_a_gee`

DESCRIPTION
=> 685 Update description after release tag added

R/tm_a_gee.R
=> 696 Add table titles to `tm_a_gee` report cards

R/tm_t_pp_prior_medication.R
My commits to https://github.com/insightsengineering/teal.modules.clinical/pull/699
=> mb tmc shinyvalidate

R/arm_ref_comp.R, R/tm_g_barchart_simple.R, R/tm_g_forest_rsp.R, R/tm_g_pp_adverse_events.R, R/tm_g_pp_patient_timeline.R, R/tm_g_pp_therapy.R, R/tm_g_pp_vitals.R, R/tm_t_abnormality.R, R/tm_t_abnormality_by_worst_grade.R, R/tm_t_ancova.R, R/tm_t_binary_outcome.R, R/tm_t_exposure.R, R/tm_t_logistic.R, R/tm_t_mult_events.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_medical_history.R, R/tm_t_smq.R, man/arm_ref_comp_observer.Rd, man/tm_t_abnormality_by_worst_grade.Rd
=> contribution AC

DESCRIPTION, NEWS.md, R/tm_a_mmrm.R, inst/WORDLIST, man/template_fit_mmrm.Rd, man/tm_a_mmrm.Rd, tests/testthat/test-tm_a_mmrm.R
Waiting for https://github.com/insightsengineering/tern.mmrm/pull/140 to be merged.
=> Updates tm_a_mmrm for new tern.mmrm/mmrm packages

.github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml
Solves these two issues:
https://github.com/insightsengineering/idr-tasks/issues/477
https://github.com/insightsengineering/idr-tasks/issues/478
=> Check as-cran + default landing page

R/tm_a_gee.R
=> adding two mo correlation struct, close #716

R/tm_a_gee.R, man/tm_a_gee.Rd, tests/testthat/_snaps/utils.md
No changes needed to code, can already handle interaction terms. Added an interaction term to the example.
closes #738
=> Updating GEE example with interaction term.

NEWS.md, R/utils.R, man/cs_to_des_filter.Rd, man/cs_to_des_select.Rd, man/cs_to_filter_spec.Rd, man/cs_to_select_spec.Rd
=> Add label option for filtering/selection fields

R/tm_g_lineplot.R, R/tm_t_abnormality_by_worst_grade.R
Fixes #757 
This also fixes a bug happening when no screening was included.
I am wondering what is the current way to add regression tests. Probably here it is not necessary anyhow
=> Fixing `tm_g_lineplot` for droplevels strata and screening character

NEWS.md, R/tm_t_exposure.R, tests/testthat/_snaps/tm_g_lineplot.md, tests/testthat/_snaps/tm_t_abnormality_by_worst_grade.md, tests/testthat/_snaps/tm_t_exposure.md, tests/testthat/_snaps/utils.md
Blocked by https://github.com/insightsengineering/tern/pull/916
Closes #766
=> Update `tm_t_exposure` to use `analyze_patients_exposure_in_cols`

R/teal.modules.clinical.R, man/template_g_km.Rd
=> Fix R CMD Check note

NEWS.md, R/tm_t_ancova.R, R/tm_t_binary_outcome.R, R/tm_t_events_by_grade.R, R/tm_t_logistic.R, R/tm_t_tte.R, inst/WORDLIST, man/tm_t_ancova.Rd, man/tm_t_binary_outcome.Rd, man/tm_t_logistic.Rd, man/tm_t_tte.Rd, tests/testthat/_snaps/tm_t_events_by_grade.md, tests/testthat/test-tm_t_events_by_grade.R
Closes https://github.com/insightsengineering/sme-tasks/issues/175
=> Remove mentions of STREAM from documentation

DESCRIPTION, NEWS.md, R/tm_t_abnormality_by_worst_grade.R, tests/testthat/_snaps/tm_t_abnormality_by_worst_grade.md
Error is caused by a limitation in `trim_levels_to_map` that cannot currently be avoided if all grade levels must always be displayed.
Closes #706
=> Improve `tm_t_abnormality_by_worst_grade` error message

NEWS.md, R/tm_t_events_patyear.R, man/template_g_lineplot.Rd, man/tm_g_lineplot.Rd, tests/testthat/_snaps/tm_t_events_patyear.md, tests/testthat/test-tm_t_events_patyear.R
=> Update `control_incidence_rate` param names in `tm_t_events_patyear`

tests/testthat/_snaps/tm_t_events_by_grade.md
=> Fix snapshot tests

NEWS.md, R/tm_g_km.R, man/template_g_km.Rd
=> Improve default annotation table sizing in `tm_g_km`

R/tm_t_pp_basic_info.R, R/tm_t_pp_laboratory.R, R/tm_t_pp_prior_medication.R
=> 803 page length

tests/testthat/_snaps/tm_g_km.md
=> update snapshot 

NEWS.md, R/tm_t_exposure.R, man/template_exposure.Rd, man/tm_t_exposure.Rd, tests/testthat/_snaps/tm_t_exposure.md
=> Refactor `tm_t_exposure` to remove summary row

NEWS.md, R/tm_t_events.R, tests/testthat/_snaps/tm_t_events.md
=> Solution for maintaining indent after pruning 

NEWS.md, R/tm_t_coxreg.R, tests/testthat/_snaps/tm_t_coxreg.md
=> Fix bug in `tm_t_coxreg` when no covariates selected

R/tm_a_mmrm.R, R/tm_g_pp_patient_timeline.R, R/tm_t_events.R, R/tm_t_logistic.R, R/tm_t_mult_events.R, R/tm_t_tte.R
Corrects SuperLinter errors that were already in `main` and unrelated to #835 
They were caught by SuperLinter because we changed the files.
=> Corrects linter errors detected on `198_card_labels@main`

R/tm_t_tte.R
Example app
```
ADTTE <- tmc_ex_adtte
ref = "ARM B",
),
ARM = list(
)
)
app <- init(
ADSL = ADSL,
ADTTE = ADTTE,
code = "
ADTTE <- tmc_ex_adtte
"
),
tm_t_tte(
label = "Time To Event Table",
dataname = "ADTTE",
variable_choices(ADSL, c("ARM", "ARMCD", "ACTARMCD")),
"ARM"
),
value_choices(ADTTE, "PARAMCD", "PARAM"),
"OS"
),
strata_var = choices_selected(
variable_choices(ADSL, c("SEX", "BMRKR2")),
"SEX"
),
time_points = choices_selected(c(182, 243), 182),
event_desc_var = choices_selected( …
```
=> `tdata` to `teal_data` - `tm_t_tte`

R/tm_t_mult_events.R
```
ADCM <- tmc_ex_adcm
adcm_keys <- c("STUDYID", "USUBJID", "ASTDTM", "CMSEQ", "ATC1", "ATC2", "ATC3", "ATC4")
join_keys <- default_cdisc_join_keys[c("ADSL", "ADCM")]
join_keys["ADCM", "ADCM"] <- adcm_keys
app <- teal::init(
ADSL = ADSL,
ADCM = ADCM,
code = "
ADCM <- tmc_ex_adcm
",
join_keys = join_keys
),
tm_t_mult_events(
label = "Concomitant Medications by Medication Class and Preferred Name",
dataname = "ADCM",
arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
seq_var = choices_selected("CMSEQ", selected = "CMSEQ", fixed = TRUE),
hlt = choices_selected(
choices = variable_choices(ADCM, c("ATC1", "ATC2", "ATC3", "ATC4")),
selected = c("ATC1", "ATC2", "ATC3", "ATC4")
),
llt = …
```
=> `tdata` to `teal_data` - `tm_t_mult_events`

R/tm_t_pp_basic_info.R
```
app <- init(
ADSL = ADSL,
code = "ADSL <- tmc_ex_adsl"
),
tm_t_pp_basic_info(
label = "Basic Info",
dataname = "ADSL",
vars = choices_selected(
choices = variable_choices(ADSL),
selected = c("ARM", "AGE", "SEX", "COUNTRY", "RACE", "EOSSTT")
)
)
)
)
```
=> `tdata` to `teal_data` - `tm_t_pp_basic_info`

R/tm_t_pp_laboratory.R
```
ADLB <- tmc_ex_adlb
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb
"
),
tm_t_pp_laboratory(
label = "Vitals",
choices = variable_choices(ADLB, "PARAMCD"),
selected = "PARAMCD"
),
param = choices_selected(
choices = variable_choices(ADLB, "PARAM"),
selected = "PARAM"
),
timepoints = choices_selected(
choices = variable_choices(ADLB, "ADY"),
selected = "ADY"
),
anrind = choices_selected(
choices = variable_choices(ADLB, "ANRIND"),
selected = "ANRIND"
),
aval = choices_selected(
choices = variable_choices(ADLB, "AVAL"),
selected = "AVAL"
),
avalu = choices_selected(
choices = variable_choices(ADLB, …
```
=> `tdata` to `teal_data` - `tm_t_pp_laboratory`

R/tm_t_pp_medical_history.R
```
ADMH <- tmc_ex_admh
app <- init(
ADSL = ADSL,
ADMH = ADMH,
code = "
ADMH <- tmc_ex_admh
"
),
tm_t_pp_medical_history(
label = "Medical History",
dataname = "ADMH",
mhterm = choices_selected(
choices = variable_choices(ADMH, c("MHTERM")),
selected = "MHTERM"
),
mhbodsys = choices_selected(
choices = variable_choices(ADMH, "MHBODSYS"),
selected = "MHBODSYS"
),
mhdistat = choices_selected(
choices = variable_choices(ADMH, "MHDISTAT"),
selected = "MHDISTAT"
)
)
)
)
```
=> `tdata` to `teal_data` - `tm_t_pp_medical_history`

R/tm_t_pp_prior_medication.R
```
ADCM <- tmc_ex_adcm
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADCM$USUBJID)
ADCM$CMASTDTM <- ADCM$ASTDTM
ADCM$CMAENDTM <- ADCM$AENDTM
adcm_keys <- c("STUDYID", "USUBJID", "ASTDTM", "CMSEQ", "ATC1", "ATC2", "ATC3", "ATC4")
join_keys <- default_cdisc_join_keys[c("ADSL", "ADCM")]
join_keys["ADCM", "ADCM"] <- adcm_keys
app <- init(
ADSL = ADSL,
ADCM = ADCM,
code = "
ADCM <- tmc_ex_adcm
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADCM$USUBJID)
ADCM$CMASTDTM <- ADCM$ASTDTM
ADCM$CMAENDTM <- ADCM$AENDTM
",
join_keys = join_keys
),
tm_t_pp_prior_medication(
label = "Prior Medication",
dataname = "ADCM",
atirel = choices_selected(
choices = variable_choices(ADCM, "ATIREL"), …
```
=> `tdata` to `teal_data` - `tm_t_pp_prior_medication`

R/tm_a_mmrm.R
```
ARMCD = list(
ref = "ARM B",
)
)
ADQS <- tmc_ex_adqs %>%
dplyr::filter(ABLFL != "Y" & ABLFL2 != "Y") %>%
dplyr::filter(AVISIT %in% c("WEEK 1 DAY 8", "WEEK 2 DAY 15", "WEEK 3 DAY 22")) %>%
dplyr::mutate(
AVISIT = as.factor(AVISIT),
AVISITN = rank(AVISITN) %>%
as.factor() %>%
as.numeric() %>%
as.factor() #' making consecutive numeric factor
)
})
datanames <- c("ADSL", "ADQS")
app <- init(
data = data,
tm_a_mmrm(
label = "MMRM",
dataname = "ADQS",
aval_var = choices_selected(c("AVAL", "CHG"), "AVAL"),
id_var = choices_selected(c("USUBJID", "SUBJID"), "USUBJID"),
arm_var = …
```
=> `tdata` to `teal_data` - `tm_a_mmrm`

R/tm_t_shift_by_grade.R
```
ADLB <- tmc_ex_adlb
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb
"
),
tm_t_shift_by_grade(
label = "Grade Laboratory Abnormality Table",
choices = variable_choices(ADSL, subset = c("ARM", "ARMCD")),
),
choices = value_choices(ADLB, "PARAMCD", "PARAM"),
selected = "ALT"
),
worst_flag_var = choices_selected(
choices = variable_choices(ADLB, subset = c("WGRLOVFL", "WGRLOFL", "WGRHIVFL", "WGRHIFL")),
selected = c("WGRLOVFL")
),
worst_flag_indicator = choices_selected(
value_choices(ADLB, "WGRLOVFL"),
selected = "Y", fixed = TRUE
),
anl_toxgrade_var = choices_selected(
choices = …
```
=> `tdata` to `teal_data` - `tm_t_shift_by_grade`

R/tm_t_summary_by.R
```
ADLB <- tmc_ex_adlb
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb
"
),
tm_t_summary_by(
label = "Summary by Row Groups Table",
choices = variable_choices(ADSL, c("ARM", "ARMCD")),
),
add_total = TRUE,
by_vars = choices_selected(
choices = variable_choices(ADLB, c("PARAM", "AVISIT")),
selected = c("AVISIT")
),
summarize_vars = choices_selected(
choices = variable_choices(ADLB, c("AVAL", "CHG")),
selected = c("AVAL")
),
useNA = "ifany",
choices = value_choices(ADLB, "PARAMCD", "PARAM"),
selected = "ALT"
)
)
)
)
```
=> `tdata` to `teal_data` - `tm_t_summary_by`

R/tm_g_barchart_simple.R
```
dplyr::mutate(ITTFL = factor("Y") %>%
formatters::with_label("Intent-To-Treat Population Flag"))
ADAE <- tmc_ex_adae %>%
dplyr::filter(!((AETOXGR == 1) & (AESEV == "MILD") & (ARM == "A: Drug X")))
app <- init(
ADSL = ADSL,
ADAE = ADAE,
code = "ADSL <- tmc_ex_adsl %>%
dplyr::mutate(ITTFL = factor(\"Y\") %>%
formatters::with_label(\"Intent-To-Treat Population Flag\"))
ADAE <- tmc_ex_adae %>%
dplyr::filter(!((AETOXGR == 1) & (AESEV == \"MILD\") & (ARM == \"A: Drug X\")))"
),
tm_g_barchart_simple(
label = "ADAE Analysis",
x = data_extract_spec(
dataname = "ADSL",
select = select_spec(
choices = variable_choices(
ADSL,
c(
"ARM", "ACTARM", "SEX",
"RACE", "ITTFL", "SAFFL", "STRATA2"
)
),
selected …
```
=> `tdata` to `teal_data` - `tm_g_barchart_simple`

R/tm_t_events_summary.R
```
dplyr::mutate(
DTHFL = dplyr::case_when( #' nolint
!is.na(DTHDT) ~ "Y",
TRUE ~ ""
) %>% formatters::with_label("Subject Death Flag")
)
add_event_flags <- function(dat) {
dat <- dat %>%
dplyr::mutate(
TMPFL_SER = AESER == "Y",
TMPFL_REL = AEREL == "Y",
TMPFL_GR5 = AETOXGR == "5",
TMP_SMQ01 = !is.na(SMQ01NAM),
TMP_SMQ02 = !is.na(SMQ02NAM),
TMP_CQ01 = !is.na(CQ01NAM)
)
column_labels <- list(
TMPFL_SER = "Serious AE",
TMPFL_REL = "Related AE",
TMPFL_GR5 = "Grade 5 AE",
TMP_SMQ01 = aesi_label(dat[["SMQ01NAM"]], dat[["SMQ01SC"]]),
TMP_SMQ02 = aesi_label("Y.9.9.9.9/Z.9.9.9.9 AESI"),
TMP_CQ01 = aesi_label(dat[["CQ01NAM"]])
)
formatters::var_labels(dat)[names(column_labels)] <- …
```
=> `tdata` to `teal_data` - `tm_t_events_summary`

R/tm_t_exposure.R
```
ADEX <- tmc_ex_adex
set.seed(1, kind = "Mersenne-Twister")
labels <- formatters::var_labels(ADEX, fill = FALSE)
ADEX <- ADEX %>%
dplyr::distinct(USUBJID, .keep_all = TRUE) %>%
dplyr::mutate(
PARAMCD = "TDURD",
PARAM = "Overall duration (days)",
AVAL = sample(x = seq(1, 200), size = dplyr::n(), replace = TRUE),
AVALU = "Days"
) %>%
dplyr::bind_rows(ADEX)
formatters::var_labels(ADEX) <- labels
})
datanames <- c("ADSL", "ADEX")
app <- init(
data = data,
tm_t_exposure(
label = "Duration of Exposure Table",
dataname = "ADEX",
choices = value_choices(data[["ADEX"]], "PARAMCD", …
```
=> `tdata` to` teal_data` - `tm_t_exposure`

R/tm_g_ci.R
```
ADLB <- tmc_ex_adlb
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb
"
),
tm_g_ci(
label = "Confidence Interval Plot",
x_var = data_extract_spec(
dataname = "ADSL",
select = select_spec(
choices = c("ARMCD", "BMRKR2"),
selected = c("ARMCD"),
multiple = FALSE,
fixed = FALSE
)
),
y_var = data_extract_spec(
filter = list(
filter_spec(
vars = "PARAMCD",
choices = levels(ADLB$PARAMCD),
selected = levels(ADLB$PARAMCD)[1],
multiple = FALSE,
label = "Select lab:"
),
filter_spec(
vars = "AVISIT",
choices = levels(ADLB$AVISIT),
selected = levels(ADLB$AVISIT)[1],
multiple = FALSE,
label = "Select visit:"
)
),
select = select_spec(
label = …
```
=> `tdata` to `teal_data` - `tm_g_ci`

R/tm_g_ci.R
Reverts insightsengineering/teal.modules.clinical#873
=> Revert "`tdata` to `teal_data` - `tm_g_ci`"

R/tm_t_events_patyear.R
```
ADAETTE <- tmc_ex_adaette %>%
dplyr::filter(PARAMCD %in% c("AETTE1", "AETTE2", "AETTE3")) %>%
dplyr::mutate(is_event = CNSR == 0) %>%
dplyr::mutate(n_events = as.integer(is_event))
app <- init(
ADSL = ADSL,
ADAETTE = ADAETTE,
code = "
ADAETTE <- tmc_ex_adaette %>%
dplyr::filter(PARAMCD %in% c(\"AETTE1\", \"AETTE2\", \"AETTE3\")) %>%
dplyr::mutate(is_event = CNSR == 0) %>%
dplyr::mutate(n_events = as.integer(is_event))
"
),
tm_t_events_patyear(
label = "AE Rate Adjusted for Patient-Years At Risk Table",
dataname = "ADAETTE",
choices = variable_choices(ADSL, c("ARM", "ARMCD")),
selected = "ARMCD"
),
add_total = TRUE,
events_var = choices_selected(
choices = …
```
=> `tdata` to `teal_data` - `tm_t_events_patyear`

R/tm_t_abnormality_by_worst_grade.R
Example App
```r
ADLB <- tmc_ex_adlb %>%
dplyr::filter(!AVISIT %in% c("SCREENING", "BASELINE"))
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb %>%
dplyr::filter(!AVISIT %in% c(\"SCREENING\", \"BASELINE\"))
"
),
tm_t_abnormality_by_worst_grade(
label = "Laboratory Test Results with Highest Grade Post-Baseline",
choices = variable_choices(ADSL, subset = c("ARM", "ARMCD")),
),
choices = value_choices(ADLB, "PARAMCD", "PARAM"),
selected = c("ALT", "CRP", "IGA")
),
add_total = FALSE
)
),
filter = teal_slices(
teal_slice("ADSL", "SAFFL", selected = "Y"),
teal_slice("ADLB", "ONTRTFL", selected = "Y")
)
)
if …
```
=> `tdata` to `teal_data` - `tm_t_abnormality_by_worst_grade`

R/tm_t_abnormality.R
```R
ADLB <- tmc_ex_adlb %>%
dplyr::mutate(
ONTRTFL = dplyr::case_when(
AVISIT %in% c("SCREENING", "BASELINE") ~ "",
TRUE ~ "Y"
) %>% formatters::with_label("On Treatment Record Flag")
)
})
datanames <- c("ADSL", "ADLB")
app <- init(
data = data,
tm_t_abnormality(
label = "Abnormality Table",
choices = variable_choices(data[["ADSL"]], subset = c("ARM", "ARMCD")),
),
add_total = FALSE,
by_vars = choices_selected(
choices = variable_choices(data[["ADLB"]], subset = c("LBCAT", "PARAM", "AVISIT")),
selected = c("LBCAT", "PARAM"),
keep_order = TRUE
),
baseline_var = …
```
=> `tdata` to `teal_data` - `tm_t_abnormality`

R/tm_g_lineplot.R
```r
ADLB <- tmc_ex_adlb %>% dplyr::mutate(AVISIT == forcats::fct_reorder(AVISIT, AVISITN, min))
app <- init(
ADSL = ADSL,
ADLB = ADLB,
code = "
ADLB <- tmc_ex_adlb %>% dplyr::mutate(AVISIT == forcats::fct_reorder(AVISIT, AVISITN, min))
"
),
tm_g_lineplot(
label = "Line Plot",
strata = choices_selected(
variable_choices(ADSL, c("ARM", "ARMCD", "ACTARMCD")),
"ARM"
),
y = choices_selected(
variable_choices(ADLB, c("AVAL", "BASE", "CHG", "PCHG")),
"AVAL"
),
param = choices_selected(
value_choices(ADLB, "PARAMCD", "PARAM"),
"ALT"
)
)
)
)
if (interactive()) {
shinyApp(ui = app$ui, server = app$server)
}
```
=> `tdata` to `teal_data` - `tm_g_lineplot`

R/tm_g_pp_therapy.R
```r
ADCM <- tmc_ex_adcm
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADCM$USUBJID)
ADCM$CMASTDTM <- ADCM$ASTDTM
ADCM$CMAENDTM <- ADCM$AENDTM
adcm_keys <- c("STUDYID", "USUBJID", "ASTDTM", "CMSEQ", "ATC1", "ATC2", "ATC3", "ATC4")
join_keys <- default_cdisc_join_keys[c("ADSL", "ADCM")]
join_keys["ADCM", "ADCM"] <- adcm_keys
app <- init(
ADSL = ADSL,
ADCM = ADCM,
code = "
ADCM <- tmc_ex_adcm
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADCM$USUBJID)
ADCM$CMASTDTM <- ADCM$ASTDTM
ADCM$CMAENDTM <- ADCM$AENDTM
",
join_keys = join_keys
),
tm_g_pp_therapy(
label = "Therapy",
dataname = "ADCM",
plot_height = c(600L, 200L, 2000L),
atirel = choices_selected(
choices = …
```
=> `tdata` to `teal_data` - `tm_g_pp_therapy`

R/tm_g_pp_adverse_events.R
```r
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADAE$USUBJID)
app <- init(
ADSL = ADSL,
ADAE = ADAE,
code = "
ADSL <- tmc_ex_adsl %>% dplyr::filter(USUBJID %in% ADAE$USUBJID)
"
),
tm_g_pp_adverse_events(
label = "Adverse Events",
dataname = "ADAE",
plot_height = c(600L, 200L, 2000L),
aeterm = choices_selected(
choices = variable_choices(ADAE, "AETERM"),
selected = "AETERM"
),
tox_grade = choices_selected(
choices = variable_choices(ADAE, "AETOXGR"),
selected = "AETOXGR"
),
causality = choices_selected(
choices = variable_choices(ADAE, "AEREL"),
selected = "AEREL"
),
outcome = choices_selected(
choices = …
```
=> `tdata` to `teal_data` - `tm_g_pp_adverse_events`

R/tm_g_forest_rsp.R
```r
dplyr::mutate(AVALC = tern::d_onco_rsp_label(AVALC) %>%
formatters::with_label("Character Result/Finding")) %>%
dplyr::filter(PARAMCD != "OVRINV" | AVISIT == "FOLLOW UP")
ARM = list(
),
ARMCD = list(
ref = "ARM B",
)
)
app <- init(
ADSL = ADSL,
ADRS = ADRS,
code = "
dplyr::mutate(AVALC = tern::d_onco_rsp_label(AVALC) %>%
formatters::with_label(\"Character Result/Finding\")) %>%
dplyr::filter(PARAMCD != \"OVRINV\" | AVISIT == \"FOLLOW UP\")
"
),
tm_g_forest_rsp(
label = "Forest Response",
dataname = "ADRS",
arm_var = …
```
=> `tdata` to `teal_data` - `tm_g_forest_rsp`

R/tm_g_km.R
```r
ADTTE <- tmc_ex_adtte
ref = "ARM B",
),
ARM = list(
)
)
app <- init(
ADSL = ADSL,
ADTTE = ADTTE,
code = "
ADTTE <- tmc_ex_adtte
"
),
tm_g_km(
label = "Kaplan-Meier Plot",
dataname = "ADTTE",
variable_choices(ADSL, c("ARM", "ARMCD", "ACTARMCD")),
"ARM"
),
value_choices(ADTTE, "PARAMCD", "PARAM"),
"OS"
),
strata_var = choices_selected(
variable_choices(ADSL, c("SEX", "BMRKR2")),
"SEX"
),
facet_var = choices_selected(
variable_choices(ADSL, c("SEX", "BMRKR2")),
NULL
) …
```
=> `tdata` to `teal_data` - `tm_g_km`

R/tm_t_coxreg.R
```
ref = "ARM B",
),
ARM = list(
)
)
ADTTE <- tmc_ex_adtte
})
datanames <- c("ADSL", "ADTTE")
app <- init(
data = data,
tm_t_coxreg(
label = "Cox Reg.",
dataname = "ADTTE",
arm_var = choices_selected(c("ARM", "ARMCD", "ACTARMCD"), "ARM"),
value_choices(data[["ADTTE"]], "PARAMCD", "PARAM"), "OS"
),
strata_var = choices_selected(
c("COUNTRY", "STRATA1", "STRATA2"), "STRATA1"
),
cov_var = choices_selected(
c("AGE", "BMRKR1", …
```
=> `tdata` to` teal_data` - `tm_t_coxreg`

R/tm_t_binary_outcome.R
```r
dplyr::mutate(
AVALC = tern::d_onco_rsp_label(AVALC) %>%
formatters::with_label("Character Result/Finding")
) %>%
dplyr::filter(PARAMCD != "OVRINV" | AVISIT == "FOLLOW UP")
ARMCD = list(ref = "ARM B", comp = c("ARM A", "ARM C")),
ARM = list(ref = "B: Placebo", comp = c("A: Drug X", "C: Combination"))
)
app <- init(
ADSL = ADSL,
ADRS = ADRS,
code = "
dplyr::mutate(
AVALC = tern::d_onco_rsp_label(AVALC) %>%
formatters::with_label(\"Character Result/Finding\")
) %>%
dplyr::filter(PARAMCD != \"OVRINV\" | AVISIT == \"FOLLOW UP\")
"
),
tm_t_binary_outcome(
label = "Responders",
dataname = "ADRS",
choices = …
```
=> `tdata` to `teal_data` - `tm_t_binary_outcome`

R/tm_g_pp_vitals.R
**Example app**
```r
ADVS <- tmc_ex_advs
app <- init(
ADSL = ADSL,
ADVS = ADVS,
code = "
ADVS <- tmc_ex_advs
"
),
tm_g_pp_vitals(
label = "Vitals",
dataname = "ADVS",
plot_height = c(600L, 200L, 2000L),
choices = variable_choices(ADVS, "PARAMCD"),
selected = "PARAMCD"
),
xaxis = choices_selected(
choices = variable_choices(ADVS, "ADY"),
selected = "ADY"
),
aval = choices_selected(
choices = variable_choices(ADVS, "AVAL"),
selected = "AVAL"
)
)
)
)
if (interactive()) {
}
```
=> `tdata` to `teal_data` - `tm_g_pp_vitals`

DESCRIPTION
=> Update `tern` version

DESCRIPTION
=> bump `teal.reporter` dep version

R/tm_t_tte.R, tests/testthat/_snaps/tm_t_tte.md
Fixes #904
Fixes `tm_t_tte` module error.
=> Remove unused `table_names` argument from `surv_timepoint`

R/tm_g_pp_adverse_events.R, R/tm_g_pp_therapy.R, R/tm_t_pp_basic_info.R, R/tm_t_pp_prior_medication.R
part of https://github.com/insightsengineering/teal.data/issues/231
=> 231 remove get_labels function

R/tm_t_summary.R, R/tm_t_summary_by.R, tests/testthat/_snaps/tm_t_summary.md, tests/testthat/_snaps/tm_t_summary_by.md
linked to https://github.com/insightsengineering/coredev-tasks/issues/493
In the PR I allow to select two `arm` variables which add additional `split_cols_by` to the rtable call. I rearanged code little as I noticed that `tm_t_summary` and `tm_t_summary_by` are basing on similar "template". 
(@lcd2yyz, @donyunardi ) Therefore I suggest to build either one function which can be a abstraction of both.
Please check the example. 
<details>
<summary>testing app </summary>
```r
library(dplyr)
library(scda)
library(scda.2022)
library(teal)
pkgload::load_all("teal.modules.clinical")
library(sparkline)
options(shiny.useragg = FALSE)
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
ADSL …
```
=> Two arm vars

R/teal.modules.clinical.R
=> 918 update teal.modules.clinical.R with `#' @keywords internal "_PACKAGE"`

README.md, inst/WORDLIST, vignettes/teal-modules-clinical.Rmd
=> Minor improvements to README/vignettes

DESCRIPTION
=> Update DESCRIPTION teal.data (>= 0.4.0)

R/argument_convention.R, R/tm_g_pp_adverse_events.R, man/module_arguments.Rd, man/template_adverse_events.Rd, man/template_arguments.Rd, man/template_g_km.Rd, man/tm_g_pp_adverse_events.Rd
=> Clean up documentation for `tm_g_pp_adverse_events`

R/argument_convention.R, R/tm_t_pp_prior_medication.R, man/module_arguments.Rd, man/template_arguments.Rd, man/template_prior_medication.Rd, man/tm_t_pp_prior_medication.Rd
=> Clean up documentation for `tm_t_pp_prior_medication`

R/tm_g_forest_rsp.R, R/tm_g_forest_tte.R, man/template_forest_rsp.Rd, man/template_forest_tte.Rd, man/tm_g_forest_rsp.Rd, tests/testthat/_snaps/tm_g_forest_rsp.md
=> Clean up documentation for `tm_g_forest_rsp`

R/tm_t_events_summary.R, inst/WORDLIST, man/template_events_summary.Rd, man/tm_t_events_summary.Rd
=> Clean up documentation for `tm_t_events_summary`

R/argument_convention.R, R/tm_t_mult_events.R, man/template_arguments.Rd, man/template_mult_events.Rd, man/tm_t_mult_events.Rd
=> Clean up documentation for `tm_t_mult_events`

R/tm_t_tte.R, man/control_tte.Rd, man/template_tte.Rd, man/tm_t_tte.Rd
=> Clean up documentation for `tm_t_tte`

R/argument_convention.R, R/tm_t_ancova.R, man/template_ancova.Rd, man/template_arguments.Rd, man/tm_t_ancova.Rd, tests/testthat/_snaps/tm_t_events.md, tests/testthat/_snaps/tm_t_events_summary.md
=> clean up documentation for `tm_t_ancova`

R/argument_convention.R, R/tm_t_smq.R, inst/WORDLIST, man/template_arguments.Rd, man/template_smq.Rd, man/tm_t_smq.Rd
=> Clean up documentation for `tm_t_smq`

R/tm_t_abnormality_by_worst_grade.R, man/template_abnormality_by_worst_grade.Rd, man/tm_t_abnormality_by_worst_grade.Rd
=> clean up documentation for tm_t_abnormality_by_worst_grade

R/tm_t_abnormality.R, man/template_abnormality.Rd, man/tm_t_abnormality.Rd
=> clean up tm_t_abnormality documentation

R/tm_g_km.R, man/template_g_km.Rd, man/tm_g_km.Rd
=> Clean up `tm_g_km` documentation

R/argument_convention.R, R/tm_g_ipp.R, R/tm_t_binary_outcome.R, R/tm_t_events_patyear.R, R/tm_t_exposure.R, man/module_arguments.Rd, man/template_arguments.Rd, man/template_events_patyear.Rd, man/tm_g_ipp.Rd, man/tm_t_events_patyear.Rd, man/tm_t_exposure.Rd
=> Clean up documentation for `tm_t_events_patyear`

R/tm_g_forest_rsp.R, R/tm_g_forest_tte.R, man/template_forest_rsp.Rd, man/template_forest_tte.Rd, man/tm_g_forest_tte.Rd
=> Clean up documentation for `tm_g_forest_tte`

R/tm_g_barchart_simple.R, man/make_barchart_simple_call.Rd, man/tm_g_barchart_simple.Rd
=> Clean up documentation for `tm_g_barchart_simple`

R/argument_convention.R, R/tm_t_events_by_grade.R, man/template_arguments.Rd, man/template_events_by_grade.Rd, man/template_events_col_by_grade.Rd, man/tm_t_events_by_grade.Rd
=> clean up documentation for `tm_t_events_by_grade`. 

DESCRIPTION
part of https://github.com/insightsengineering/teal.modules.clinical/issues/919
Fixes #nnn
=> Update DESCRIPTION teal 0.15.0

R/tm_t_shift_by_arm.R
=> Fix assertion on paramcd

R/tm_g_pp_patient_timeline.R
=> Clarify `tm_g_pp_patient_timeline` error message

DESCRIPTION, man/teal.modules.clinical.Rd, vignettes/quickstart_substitute.Rmd, vignettes/teal-modules-clinical.Rmd
=> final prerelease activities

DESCRIPTION
=> Update DESCRIPTION teal.transform >= 0.5.0

R/utils.R, man/bracket_expr.Rd, man/call_concatenate.Rd, man/clean_description.Rd, man/color_lab_values.Rd, man/extract_input.Rd, man/pipe_expr.Rd, man/prepare_arm.Rd, man/prepare_arm_levels.Rd, man/split_choices.Rd, man/split_col_expr.Rd, man/split_interactions.Rd
Fixes #1074
Also added examples where missing to the listed functions.
Do we want to merge this into main or the CRAN release branch?
=> Add missing return values

DESCRIPTION, NEWS.md, R/tm_g_km.R, inst/WORDLIST, man/template_g_km.Rd, man/tm_g_km.Rd, tests/testthat/_snaps/tm_g_km.md
=> Update `tm_g_km` after `g_km` refactor

R/tm_g_lineplot.R, tests/testthat/_snaps/tm_g_lineplot.md
=> Replace use of deprecated `control_summarize_vars`

man/template_forest_rsp.Rd, man/template_g_km.Rd, man/template_g_lineplot.Rd, man/template_logistic.Rd, man/tm_g_forest_rsp.Rd, man/tm_g_forest_tte.Rd, man/tm_g_km.Rd, man/tm_g_lineplot.Rd, vignettes/quickstart_substitute.Rmd
According to the [docs](https://r-pkgs.org/R-CMD-check.html#:~:text=Checking%20running%20R%20code%20from%20vignettes)
> If you want to deliberately execute errors (to show the user what failure looks like), make sure the chunk has error = TRUE, purl = FALSE
=> error=T, purl=F in expected errors in vignettes

DESCRIPTION
=> checking aligning to the latest versions

tests/testthat/helper-TealAppDriver.R, tests/testthat/helper-testing-depth.R
Part of #1108
- Adds necessary functions for e2e tests on modules
=> Adds `TealAppDriver` and `skip_if_too_deep` for e2e testing

tests/testthat/helper-TealAppDriver.R, tests/testthat/test-shinytest2-tm_g_barchart_simple.R
Helper functions to test whether plot or table were changed, based on a value change in specific input.
=> Wave 1 - `test_table_changes_no_errors` and `test_plot_changes_no_errors`

DESCRIPTION, NEWS.md
=> [skip vbump] preping for cran release

tests/testthat/test-shinytest2-tm_a_mmrm.R
Add `fit_model` to `app_driver_tm_a_mmrm` so that the click automatically happens when the app driver is created
=> Add `fit_model` to `app_driver_tm_a_mmrm`

tests/testthat/test-shinytest2-tm_t_tte.R
=> Wave 7 - `tm_t_tte` shinytests

tests/testthat/test-shinytest2-tm_t_summary_by.R
=> Wave 7 - `tm_t_summary_by` shinytests

tests/testthat/test-shinytest2-tm_t_summary.R
=> Wave 7 - `tm_t_summary` shinytests

tests/testthat/test-shinytest2-tm_t_smq.R
=> Wave 7 - `tm_t_smq` shinytests

tests/testthat/test-shinytest2-tm_t_shift_by_grade.R
=> Wave 7 - `tm_t_shift_by_grade` shinytests

tests/testthat/test-shinytest2-tm_t_shift_by_arm_by_worst.R
=> Wave 7 - `tm_t_shift_by_arm_by_worst` shinytests

tests/testthat/test-shinytest2-tm_t_abnormality.R
=> Wave 3 - `tm_t_abnormality` shinytest2

tests/testthat/test-shinytest2-tm_t_pp_basic_info.R
=> Wave 6 - `tm_t_pp_basic_info` shinytests

tests/testthat/test-shinytest2-tm_t_pp_medical_history.R
=> Wave 6 - `tm_t_pp_medical_history` shinytests

tests/testthat/test-shinytest2-tm_t_pp_prior_medication.R
=> Wave 6 - `tm_t_pp_prior_medication` shinytests

tests/testthat/test-shinytest2-tm_t_shift_by_arm.R
=> Wave 6 - `tm_t_shift_by_arm` shinytests

tests/testthat/test-shinytest2-tm_g_pp_patient_timeline.R
=> Wave 3 - `tm_g_pp_patient_timeline` shinytest2 

tests/testthat/test-shinytest2-tm_t_events_patyear.R
=> Wave 5 - `tm_t_events_patyear` shinytests

tests/testthat/test-shinytest2-tm_t_logistic.R
=> Wave 5 - `tm_t_logistic` shinytests

tests/testthat/test-shinytest2-tm_t_mult_events.R
=> Wave 5 - `tm_t_mult_events` shinytests

tests/testthat/test-shinytest2-tm_t_coxreg.R
=> Wave 4 - `tm_t_coxreg` shinytests

tests/testthat/test-shinytest2-tm_t_events.R
=> Wave 4 - `tm_t_events` shinytests

tests/testthat/test-shinytest2-tm_t_events_by_grade.R
=> Wave 4 - `tm_t_events_by_grade` shinytests

tests/testthat/test-shinytest2-tm_g_pp_adverse_events.R
=> Wave2 - `tm_g_pp_adverse_events` shinytests

tests/testthat/test-shinytest2-tm_t_abnormality_by_worst_grade.R
=> Wave 3 - `tm_t_abnormality_by_worst_grade` shinytest2

tests/testthat/test-shinytest2-tm_t_exposure.R
=> Wave 5 - `tm_t_exposure` shinytests

DESCRIPTION
=> truetype font support checking PR

DESCRIPTION, NEWS.md, R/argument_convention.R, R/tm_t_events.R, R/tm_t_events_summary.R, R/tm_t_smq.R, R/tm_t_summary.R, R/tm_t_summary_by.R, man/module_arguments.Rd, man/tm_a_gee.Rd, man/tm_a_mmrm.Rd, man/tm_g_forest_rsp.Rd, man/tm_g_forest_tte.Rd, man/tm_g_km.Rd, man/tm_t_abnormality.Rd, man/tm_t_abnormality_by_worst_grade.Rd, man/tm_t_ancova.Rd, man/tm_t_binary_outcome.Rd, man/tm_t_coxreg.Rd, man/tm_t_events_by_grade.Rd, man/tm_t_events_patyear.Rd, man/tm_t_mult_events.Rd, man/tm_t_shift_by_arm.Rd, man/tm_t_shift_by_arm_by_worst.Rd, man/tm_t_shift_by_grade.Rd, man/tm_t_tte.Rd
=> Fix documentation of `arm_var` argument in modules

NEWS.md, R/tm_t_events_summary.R, man/template_events_summary.Rd, man/tm_t_events_summary.Rd, tests/testthat/_snaps/tm_t_events_summary.md, tests/testthat/test-tm_t_events_summary.R
=> Add options to toggle the "Total deaths" and "Total withdrawals due to AE" rows in `tm_t_events_summary`

R/tm_t_events_summary.R
<details>
<summary>Example with decorator</summary>
```r
pkgload::load_all("./tern", export_all = FALSE)
pkgload::load_all("../teal", export_all = FALSE)
pkgload::load_all(".", export_all = FALSE)
library(dplyr)
mutate(
DTHFL = case_when(
!is.na(DTHDT) ~ "Y",
TRUE ~ ""
) %>% with_label("Subject Death Flag")
)
.add_event_flags <- function(dat) {
dat <- dat %>%
mutate(
TMPFL_SER = AESER == "Y",
TMPFL_REL = AEREL == "Y",
TMPFL_GR5 = AETOXGR == "5",
TMP_SMQ01 = !is.na(SMQ01NAM),
TMP_SMQ02 = !is.na(SMQ02NAM),
TMP_CQ01 = !is.na(CQ01NAM)
)
column_labels <- list(
TMPFL_SER = "Serious AE",
TMPFL_REL = "Related AE",
TMPFL_GR5 = "Grade 5 AE", …
```
=> Include decorators for `tm_t_events_summary`

R/tm_t_events_patyear.R, man/tm_t_events_patyear.Rd
<details>
<summary>Example with decorator</summary>
```r
devtools::load_all("../tern")
devtools::load_all("../teal")
devtools::load_all(".")
library(dplyr)
ADAETTE <- tmc_ex_adaette %>%
filter(PARAMCD %in% c("AETTE1", "AETTE2", "AETTE3")) %>%
mutate(is_event = CNSR == 0) %>%
mutate(n_events = as.integer(is_event))
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
ADSL <- data[["ADSL"]]
ADAETTE <- data[["ADAETTE"]] …
```
=> Introduce decorator for `tm_t_events_patyear`

R/tm_t_binary_outcome.R, man/tm_t_binary_outcome.Rd
<details>
<summary>Working example of the decorators</summary>
````r
load_all("../teal.code")
load_all("../teal.data")
load_all("../teal.reporter")
load_all("../teal")
load_all(".")
library(dplyr)
data <- within(teal_data(), {
mutate(
AVALC = d_onco_rsp_label(AVALC) %>%
with_label("Character Result/Finding")
) %>%
filter(PARAMCD != "OVRINV" | AVISIT == "FOLLOW UP")
})
join_keys(data) <- default_cdisc_join_keys[names(data)]
ADSL <- data[["ADSL"]]
ADRS <- data[["ADRS"]]
ui = function(id) shiny::textInput(shiny::NS(id, "new_row"), "New row", …
```
=> Introduce decorators for `tm_t_binary_outcome`

R/tm_t_pp_laboratory.R, man/tm_t_pp_laboratory.Rd
<details>
<summary>Working example</summary>
```r
pkgload::load_all("../teal.modules.clinical", export_all = FALSE)
rlisting_footer <- function(default_footer = "I am a good footer", .var_to_replace = "table") {
ui = function(id) shiny::textInput(shiny::NS(id, "footer"), "footer", value = default_footer),
substitute({
rlistings::main_footer(.var_to_replace) <- footer
)
)
}
dt_decorator <- function(.color1 = "#f9f9f9", .color2 = "#f0f0f0", .var_to_replace = "table") {
label = "Table color",
ui = function(id) {
selectInput(
NS(id, "style"),
"Table Style",
choices = …
```
=> Adds decorators to `tm_t_pp_laboratory`

DESCRIPTION
=> upversion dep

DESCRIPTION
Companion to
- https://github.com/insightsengineering/teal.modules.general/pull/834
- https://github.com/insightsengineering/teal/pull/1464
=> vbump teal.code

vignettes/teal-modules-clinical.Rmd
Part of vignette review https://github.com/insightsengineering/nestdevs-tasks/issues/99
=> Make sure the code chunks does not break because of warnings

DESCRIPTION
Vbumps teal.widgets to the newest CRAN release version
=> vbump teal.widgets

R/tm_g_pp_adverse_events.R, R/tm_t_events_by_grade.R
closes #1343 alternative to #1354
=> wrap within expr in {} to potentially cheat r cmd check

NEWS.md, R/tm_g_km.R, man/template_g_km.Rd, man/tm_g_km.Rd, tests/testthat/_snaps/tm_g_km.md, tests/testthat/test-shinytest2-tm_g_km.R
=> Add the `conf_type` argument to `tm_g_km()`

R/tm_g_pp_adverse_events.R
Part of https://github.com/insightsengineering/teal/issues/1505
=> Final UI and bslib changes

DESCRIPTION, NEWS.md
Fixes #1378 
* Update DESCRIPTION and NEWS
* vbump teal.* packages
* vbump tern, rtables, rlistings, tern.mmrm to latest release (per @shajoezhu suggestion)
* Remove `Remotes` entry
=> [skip vbump] upversion v0.11.0

NEWS.md, R/tm_g_ci.R, R/tm_g_km.R
- Fixes #1376 
- Removes 2 UI buttons that were leftover from #1392
- Adds NEWS.md section
=> Removes 2 reporter buttons
